### ISSUE TITLE
Multiple errors after domoticz update

### ISSUE THREAD

**Issue by bobox59** [999LV/SmartVirtualThermostat#10]
Since update domoticz to 4.9700
my thermostat plugin give multiple errors:
Error: (Chauffage) 'onHeartbeat' failed 'KeyError'.
Error: (Chauffage) ----> Line 599 in /home/pi/domoticz/plugins/SVT/plugin.py, function onHeartbeat
Error: (Chauffage) ----> Line 275 in /home/pi/domoticz/plugins/SVT/plugin.py, function onHeartbeat

**Comment by 999LV** [comment]
Which version of the plugin are you using ? In the latest, line 275 is:

if Devices[1].sValue == "0":

If this fails, it means device 1 (the main thermostat switch) has been deleted... and this is strange because on domoticz or plugin startup this device is created if if does not exist... please check the devices list to see if it exists

For your information I am also running domoticz lastest release without problems with this plugin.

**Comment by bobox59** [comment]
Dear,
sorry winter arrives and still have the problem
i've pulled you a correction of the plugin to show correct plugin version in logs (0.4.3 instead of 0.4.1)

still have theses errors with all lastests versions of domoticz and plugin:

2018-09-23 22:33:44.625 Error: (SVT03) 'onStart' failed 'KeyError'.
2018-09-23 22:33:44.625 Error: (SVT03) ----> Line 581 in /home/pi/domoticz/plugins/SVT/plugin.py, function onStart
2018-09-23 22:33:44.625 Error: (SVT03) ----> Line 205 in /home/pi/domoticz/plugins/SVT/plugin.py, function onStart
and can't understand why for the moment.
