### ISSUE TITLE
Cooling mode

### ISSUE THREAD

**Issue by reydecopas** [999LV/SmartVirtualThermostat#15]
Hi, Using your plugin in my installation from early days...

Do you think it would be possible to add some kind of mode setting to allow adjust the plugin from heating mode to cooling mode for an aerotherm based heating/cooling floor?

thank you in advance!!

**Comment by 999LV** [comment]
Hi, glad you find this plugin useful. You are indeed not the first one to suggest that it handles cooling as well as heating. For now, I chose not to investigate this further, primarily due to the fact that I do not own a connected cooling device, so cannot really test such a development... 

That being said, it would also require significant additional code, since the cooler(s) are likely to have significantly different thermal characteristics than heater(s), hence a specific logic needs to be added... not impossible, but I need to find time to develop it and need testers...
