### ISSUE TITLE
Plugin get stuck 

### ISSUE THREAD

**Issue by arturf209** [999LV/SmartVirtualThermostat#17]
Hi, i use your plugin for few days, I'm more than happy but also i've got some issues. My sonoff (controls my heater) is quite far from router and sometimes loses connection with it. 

If plugin turns on heating and reaches the setpoint then sends command to turn off heating, but if my sonoff loses connection then heating is permanently ON, because plugin and domoticz think that heating is not working anymore. Temperature is slowly growing UP. 

This problem can happend other way round, plugin thinks that heating is working but temperature is not rising, so i stuck in cold house.

The question is:
Any posibility to add some function to plugin which can do a period check if temperature is rising or dropping and then do some actions? 

ex: If i stuck on command OFF then temperature will be rising or at least in worst scenario stay at the same point.

Also would be great to know if plugin checks response from sonoffs (mqtt response) - if sonoff loses connection then will not send any feedback to MQTT.

Could you look up this problem for me please?

**Comment by 999LV** [comment]
@arturf209 ,

what seems wise is to improve your network reliability :)

I think your issue is so specific that it should be best solved with a domoticz script in blockly, lua or python as you prefer. This script could for instance send a notification in case temperature raises above or below some thresholds. The domoticz forum is your place for issues like this.

Closing this issue (that is related to network reliability, not to the plugin code)
