### ISSUE TITLE
Different sensors for different time of day

### ISSUE THREAD

**Issue by pmitrus** [999LV/SmartVirtualThermostat#29]
At beginning I want to say that this is excellent plugin. 
This is rather not an issue but enhancement. Have you consider to extend number of inside temperature list to be switched as valid by timer. The solution could be enough to have different list for normal/economy mode. Solution is helpful for houses where i.e. bedrooms are on upper level and we want to keep stable temperature during night but we don't care what is in living room, and have living room as master sensor for normal mode when during day all inmates are downstairs. For old users by default only main sensor can be used when new field remains empty.

**Comment by 999LV** [comment]
Thanks for the suggestion (actually it would have been more useful for the users community to post on the domoticz forum, rather than Github ?).
I think what you want to achieve can be best implemented by having multiple instances of the plugin (for instance one for an upstairs bedroom and one for living room), each with different set points and timers.
Obviously this implies that you have discrete controllable heating source(s) in each zone covered by a thermostat and that you do not have too much leaking of heat between one zone and another if their programming differs significantly (in other words, closed doors...)
Hope this helps
